name: '1.2. infra CD for dev'

on:
  push:
    branches:
      - "main"
  workflow_dispatch:

jobs:
  cd_dev:
    name: 'cd_dev'
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
    permissions:
      id-token: write
      contents: read
    env:
      WORKLOAD_IDENTITY_PROVIDER: "projects/500315244546/locations/global/workloadIdentityPools/github-pool/providers/github-provider"
      PROJECT_ID: "tmp-20240814"

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v2
        with:
          workload_identity_provider: ${{ env.WORKLOAD_IDENTITY_PROVIDER }}
          project_id: ${{ env.PROJECT_ID }}

      - name: Detect Terraform version
        run: |
          printf "TF_VERSION=%s" $(cat .terraform-version) >> $GITHUB_ENV

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: ${{ env.TF_VERSION }}
          terraform_wrapper: false

      - name: Terraform Init
        run: terraform init
        working-directory: ./env/dev

      - name: Terraform Apply
        run: terraform apply -auto-approve
        working-directory: ./env/dev
